[package]
name = "meu-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
dotenvy = "0.15.7"
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
argon2 = "0.6.0"
sea-orm = { version = "2.0.4", features = ["sqlx-postgres", "runtime-tokio-rustls"] }


